### PR TITLE
Switch to native get_option to fix #32

### LINKED ISSUE #32: ACF 5.11 breaks plugin for user roles < administrator
I just discovered that the recently released version 5.11 of ACF breaks this plugin for users with the `editor` role.

Apparently ACF changed something about the working of `get_field( '{field}', 'option' )` when logged in as non-admin. That's why `getVimeoToken()` returns null in theses cases which breaks the search for vimeo videos.

A quick fix is to change 

https://github.com/ttillberg/acf-vimeo-pro-data/blob/master/fields/acf-vimeo_pro_data-v5.php#L120

to `return get_option('options_acf_vimeo_auth_token');` 

I'll draft a PR real quick, do you think releasing a new version would be possible in a timely manner?

### PR DESCRIPTION
**Pull request by hatsumatsu**

### CODE REVIEW

**Comment by ttillberg** [comment]
Thanks @hatsumatsu ! I'm guessing this is backwards compatible since you're using the native get_options. I wasn't aware they were interchangeable. Let's try it anyways, soft update without bumping the version.

**Comment by hatsumatsu** [comment]
> I wasn't aware they were interchangeable.

Interchangable with a prefix ;-) 
@ttillberg soft update means available via re-installing the plugin?

thx for the prompt support!!

**Comment by ttillberg** [comment]
> @ttillberg soft update means available via re-installing the plugin?

Exactly. Just want to run it through an old install first unless you've tried already? Happy to get it out there ASAP otherwise

**Comment by hatsumatsu** [comment]
> > @ttillberg soft update means available via re-installing the plugin?
> 
> Exactly. Just want to run it through an old install first unless you've tried already? Happy to get it out there ASAP otherwise

Looks alright in two installs of mine but always good to double-check.

**Pull request merged**
